# Generated by Django 3.1.7 on 2021-02-23 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0004_auto_20210223_0236'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(blank=True, max_length=64, null=True)),
                ('site', models.CharField(blank=True, max_length=64, null=True)),
                ('date', models.CharField(blank=True, max_length=64, null=True)),
                ('eventdate', models.CharField(blank=True, max_length=64, null=True)),
                ('round', models.CharField(blank=True, max_length=64, null=True)),
                ('eco', models.CharField(blank=True, max_length=5, null=True)),
                ('whiteelo', models.IntegerField(blank=True, null=True)),
                ('blackelo', models.IntegerField(blank=True, null=True)),
                ('black', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_black', to='players.player')),
                ('white', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_white', to='players.player')),
            ],
        ),
    ]
