# Generated by Django 3.1.7 on 2021-02-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='video_file',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
