# Generated by Django 3.1.7 on 2021-02-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20210223_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessgame',
            name='video_file',
            field=models.FilePathField(blank=True, null=True, path='/media/ss/BACKUP/PycharmProjects/chessShortsDjango/process/'),
        ),
    ]
