# Generated by Django 3.1.7 on 2021-02-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20210223_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='pgn',
            field=models.TextField(blank=True),
        ),
    ]
