# Generated by Django 3.1.7 on 2021-02-23 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='photo_attrib',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
