# Generated by Django 3.1.7 on 2021-02-23 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20210223_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
