# Generated by Django 3.1.7 on 2021-02-24 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_auto_20210223_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='aka',
            field=models.TextField(blank=True),
        ),
    ]
