# Generated by Django 3.1.7 on 2021-02-24 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_auto_20210224_0855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['name']},
        ),
    ]
